#pragma once

enum ItemType
{
	ITEM_STANDARD_BALL = 0,
	ITEM_SUPER_BALL = 1,
	ITEM_UBER_BALL = 2,
	ITEM_STANDARD_HEAL = 3,
	ITEM_SUPER_HEAL = 4,
	ITEM_KEG_OF_HEALTH = 5,
	ITEM_MEGA_SEED = 6,
	ITEM_EGG = 127
};
